# Generated by Django 5.1.4 on 2024-12-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-value']},
        ),
    ]
